"""
data_relabel_bter.py
--------------------

The graphs generated by feastpack_v1.2/generate_graph.m are not
labeled correctly.

"""

import os
import sys
from os import path
import networkx as nx

relabel = nx.convert_node_labels_to_integers


def largest_component(graph):
    """Return the largest component of the graph."""
    nodes = max(nx.connected_components(graph), key=len)
    return graph.subgraph(nodes).copy()


def main():
    """Read in each BTER graph and output a correctly labeled version."""
    for _, _, files in os.walk('data'):
        for fn in files:
            if fn.endswith('raw'):
                print(fn[:-4])
                graph = nx.read_edgelist(path.join('data/', fn), nodetype=int, data=False)
                graph.remove_edges_from(nx.selfloop_edges(graph))
                graph = relabel(largest_component(graph))
                nx.write_edgelist(graph, path.join('data/', fn[:-4]))



if __name__ == '__main__':
    main()
